random_state: 42

target:
  name: Churn
  positive_class: "Yes"
  negative_class: "No"

split:
  test_size: 0.2

models:
  baseline_model: logistic_regression
  advanced_model: xgboost

logistic_regression:
  max_iter: 1000
  solver: liblinear

xgboost:
  objective: binary:logistic
  eval_metric: logloss
  n_estimators: 100
  max_depth: 4
  learning_rate: 0.1
  subsample: 0.9
  colsample_bytree: 0.9

tuning:
  scoring: f1
  cv: 3
  xgboost_param_grid:
    n_estimators: [50, 100]
    max_depth: [3, 4]
    learning_rate: [0.05, 0.1]